version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Change to your required Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - npm run build

artifacts:
  files:
    - src/index.js # Adjust according to your source structure
Transform: AWS::Serverless-2016-10-31